version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.rails
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    depends_on:
      - mailcatcher
      - postgres
    env_file: .env
    networks:
      - railsnet
    ports:
      - 3000:3000
    volumes:
      - ./rails:/app
      - gem_cache:/usr/local/bundle/gems
      - node_modules:/app/node_modules

  mailcatcher:
    image: dockage/mailcatcher:0.6.5
    networks:
      - railsnet
    ports:
      - 1025:1025
      - 1080:1080

  postgres:
    image: postgres
    env_file: .env
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      PG_DATA: /var/lib/postgresql/data
    networks:
      - railsnet
    ports:
      - 5432:5432
    restart: always
    volumes:
      - ./pgdata:/var/lib/postgresql/data

networks:
  railsnet:

volumes:
  gem_cache:
  node_modules:
